/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qlvlhnsafjhaadfnqaws"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsdmxobnNhZmpoYWFkZm5xYXdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5OTgxNDEsImV4cCI6MjA3NDU3NDE0MX0.qAMg-oCKnie2HzJOhZ8tIOnZzfoVxX-FcHXSzhJgUrg"